pomodoro/standalone/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from pomodoro import rest

router = routers.DefaultRouter(trailing_slash=False)
router.register("favorites", rest.FavoriteViewSet)
router.register("pomodoros", rest.PomodoroViewSet)
router.register("project", rest.ProjectViewSet)

urlpatterns = [
    path("", include(("pomodoro.urls", "pomodoro"))),
    path("", include("django.contrib.auth.urls")),
    path("grafana/", include(("pomodoro.grafana"), namespace="grafana")),
    path("api/", include((router.urls, "api"), namespace="api")),
    path("admin/", admin.site.urls),
]

pomodoro/urls.py
from django.urls import path

from pomodoro import views

app_name = "pomodoro"
urlpatterns = [
    path("report/", views.PomodoroArchiveView.as_view(), name="pomodoro-list"),
    path("today", views.HistoryRedirect.as_view(), name="pomodoro-today"),
    path("report/<int:year>/", views.PomodoroYearView.as_view(), name="pomodoro-year"),
    path("report/<int:year>/<int:month>/", views.PomodoroMonthView.as_view(), name="pomodoro-month"),
    path("report/<int:year>/<int:month>/<int:day>/", views.PomodoroDateView.as_view(), name="pomodoro-day"),
    path("pomodoro/<int:pk>", views.PomodoroDetailView.as_view(), name="pomodoro-detail"),
    path("favorite/<int:pk>", views.FavoriteDetail.as_view(), name="favorite-detail"),
    path("favorite", views.FavoriteList.as_view(), name="favorite-list"),
    path("projects", views.ProjectList.as_view(), name="project-list"),
    path("projects/new", views.ProjectCreate.as_view(), name="project-create"),
    path("projects/<pk>", views.ProjectDetail.as_view(), name="project-detail"),
    path("projects/<pk>/update", views.ProjectUpdate.as_view(), name="project-update"),
    path("projects/<pk>/favorite", views.ProjectFavoriteCreate.as_view(), name="project-favorite-create"),
    path("", views.Index.as_view(), name="dashboard"),
    path("share", views.ShareList.as_view(), name="share-list"),
    path("share/<pk>.ics", views.ShareCalendar.as_view(), name="share-calendar"),
]

pomodoro/models.py
import datetime
import logging
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from . import fields, util

logger = logging.getLogger(__name__)


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="+",
        verbose_name=_("owner"),
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=128, verbose_name=_("name"))
    color = fields.ColorField()
    url = models.URLField(blank=True, verbose_name=_("Optional link"))
    memo = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    duration = models.IntegerField(verbose_name=_("duration"), default=0)

    class Meta:
        ordering = ("name",)
        unique_together = [["owner", "name"]]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("pomodoro:project-detail", kwargs={"pk": self.pk})

    def timedelta(self):
        return datetime.timedelta(seconds=self.duration)

    timedelta.admin_order_field = "duration"

    def refresh(self, lookback=90):
        limit = timezone.now() - datetime.timedelta(days=lookback)
        duration = datetime.timedelta()
        for pomodoro in Pomodoro.objects.filter(
            start__gte=limit,
            owner=self.owner,
            project=self,
        ):
            duration += pomodoro.end - pomodoro.start
        self.duration = duration.total_seconds()
        self.save(update_fields=("duration",))


class Pomodoro(models.Model):
    start = models.DateTimeField(default=timezone.now, verbose_name=_("start time"))
    end = models.DateTimeField(default=timezone.now, verbose_name=_("end time"))

    title = models.CharField(max_length=128, verbose_name=_("title"))
    category = models.CharField(max_length=32, blank=True, verbose_name=_("category"))
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="+",
        verbose_name=_("owner"),
        on_delete=models.CASCADE,
    )
    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)

    url = models.URLField(blank=True, help_text="Optional link")
    memo = models.TextField(blank=True)

    @property
    def duration(self):
        return self.end - self.start

    duration.fget.short_description = _("duration")

    def __str__(self):
        return f"{self.start}:{self.title}"

    def get_absolute_url(self):
        return reverse("pomodoro:pomodoro-detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ("-start",)


class Favorite(models.Model):
    duration = models.IntegerField(verbose_name=_("duration"))
    title = models.CharField(max_length=128, verbose_name=_("title"))
    category = models.CharField(max_length=32, blank=True, verbose_name=_("category"))
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="+",
        verbose_name=_("owner"),
        on_delete=models.CASCADE,
    )
    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    icon = models.ImageField(upload_to=util._upload_to_path, blank=True)
    count = models.PositiveIntegerField(default=0)
    url = models.URLField(blank=True)

    pomodoro_set = models.ManyToManyField(
        Pomodoro,
        through="FavoritePomodoro",
        through_fields=("favorite", "pomodoro"),
    )

    class Meta:
        ordering = ("-count",)

    def get_absolute_url(self):
        return reverse("pomodoro:favorite-detail", kwargs={"pk": self.pk})

    def refresh(self, lookback=90):
        search = timezone.now() - datetime.timedelta(days=lookback)
        self.count = self.pomodoro_set.filter(end__gte=search).count()
        self.save(update_fields=("count",))

    def timedelta(self):
        return datetime.timedelta(minutes=self.duration)

    def start(self, ts):
        pomodoro = Pomodoro.objects.create(
            title=self.title,
            category=self.category,
            project=self.project,
            owner=self.owner,
            start=ts,
            end=ts + datetime.timedelta(minutes=self.duration),
            url=self.url,
        )
        self.pomodoro_set.add(pomodoro)
        return pomodoro


class Share(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="+",
        verbose_name=_("owner"),
        on_delete=models.CASCADE,
    )
    last_accessed = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("pomodoro:share-calendar", kwargs={"pk": self.pk})


class FavoritePomodoro(models.Model):
    favorite = models.ForeignKey(Favorite, on_delete=models.CASCADE)
    pomodoro = models.ForeignKey(Pomodoro, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

pomodoro/templates/pomodoro/base.html
{% extends "base.html" %}
{% load static %}

{% block javascript %}
<script src="{% static '/js/pomodoro.js' %}"></script>
{% endblock %}

{% block styles %}
<link rel="apple-touch-icon" href="{% static '/images/pomodoro.png' %}">
<meta name="apple-mobile-web-app-title" content="Pomodoro">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="stylesheet" href="{% static '/css/pomodoro.css' %}">
{% endblock %}

pomodoro/templates/pomodoro/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<ul class="nav nav-pills" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" href="#pomodoro-tab" aria-controls="pomodoro-tab" data-toggle="tab">Pomodoro</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#favorite-tab" aria-controls="favorite-tab" data-toggle="tab">Favorites</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'pomodoro:history' yesterday|date:"Ymd" %}" aria-controls="history-tab">History</a>
    </li>
</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="pomodoro-tab">
        {% include 'pomodoro/block_pomodoro.html' %}
    </div>
    <div role="tabpanel" class="tab-pane" id="favorite-tab">
        {% include 'pomodoro/block_favorite.html' %}
    </div>
    <div role="tabpanel" class="tab-pane" id="history-tab">
        {% include 'pomodoro/block_history.html' %}
    </div>
</div>
{% endblock %}

{% block styles %}
<link rel="apple-touch-icon" href="{% static "images/pomodoro.png" %}">
<meta name="apple-mobile-web-app-title" content="Pomodoro">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<style type="text/css">
#clockdiv{
    font-family: sans-serif;
    display: inline-block;
    font-weight: 100;
    text-align: center;
    font-size: 1em;
}

#clockdiv > div{
    padding: 10px;
    border-radius: 3px;
    display: inline-block;
    background-color:#eee;
}

#clockdiv div > span{
    padding: 15px;
    border-radius: 3px;
    display: inline-block;
}
.smalltext{
    padding-top: 5px;
    font-size: 0.75em;
}

</style>
{% endblock %}

{% block javascript %}
<script>
/*
Based on code from
https://www.sitepoint.com/build-javascript-countdown-timer-no-dependencies/
*/
var deadline = new Date("{{ pomodoro.end.isoformat }}")

function getTimeRemaining(endtime, current){
    t = Math.abs(endtime - current);

    return {
        'total': t,
        'days': Math.floor( t/(1000*60*60*24) ),
        'hours': Math.floor( (t/(1000*60*60)) % 24 ),
        'minutes': Math.floor( (t/1000/60) % 60 ),
        'seconds': Math.floor( (t/1000) % 60 )
    };
}

function initializeClock(id, endtime){
    var clock = document.getElementById(id);
    var daysSpan = clock.querySelector('.days');
    var hoursSpan = clock.querySelector('.hours');
    var minutesSpan = clock.querySelector('.minutes');
    var secondsSpan = clock.querySelector('.seconds');

    function updateClock(){
        var current = Date.now()
        var t = getTimeRemaining(endtime, current);

        daysSpan.innerHTML = t.days
        hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
        minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
        secondsSpan.innerHTML =('0' + t.seconds).slice(-2);
    }

    updateClock(); // run function once at first to avoid delay
    var timeinterval = setInterval(updateClock, 1000);
}

initializeClock('clockdiv', deadline);
</script>
{% endblock %}

pomodoro/templates/pomodoro/favorite_form.html
{% extends "pomodoro/base.html" %}
{% load i18n %}
{% load pomodoro %}

{% block content %}

{% breadcrumb project "New Favorite" %}

<form method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <button name="duration" type="submit" value="25" class="btn btn-warning">{% trans 'Save' %}</button>
</form>

{% endblock %}

pomodoro/templates/pomodoro/index.html
{% extends "pomodoro/base.html" %}

{% block content %}
<div class="card" data-countdown="{{ pomodoro.end.isoformat }}">
    <h4 class="card-header">
        <a href="{{pomodoro.get_absolute_url}}">{{pomodoro.title}}</a>
        <small>(<a href="{{pomodoro.project.get_absolute_url}}">{{pomodoro.project.name}}</a>)</small>
    </h4>
    <div class="card-body countdown-body">
        <div class="days">
            <span></span>
            <div>Days</div>
        </div>
        <div class="hours">
            <span></span>
            <div>Hours</div>
        </div>
        <div class="minutes">
            <span></span>
            <div>Minutes</div>
        </div>
        <div class="seconds">
            <span></span>
            <div>Seconds</div>
        </div>
    </div>
    <form action="" method="post">{% csrf_token %}
        <table class="table">
            <tr>
                <td>Start</td>
                <td>{{ pomodoro.start }}</td>
            </tr>
            <tr>
                <td>End</td>
                <td>{{ pomodoro.end }}</td>
            </tr>
            {% if not active %}
            <tr>
                <td>{{form.title.label}}</td>
                <td>{{form.title}}</td>
                <td>{{form.title.error}}</td>
            </tr>
            <tr>
                <td>{{form.project.label}}</td>
                <td>{{form.project}}</td>
                <td>{{form.project.error}}</td>
        </table>
        <div class="card-body">
            <button name="duration" type="submit" value="25" class="btn btn-primary btn-block">25 Minute</button>
            <button name="duration" type="submit" value="60" class="btn btn-primary btn-block">1 Hour</button>
        </div>
        {% else %}
        </table>
        <div class="card-body">
            <button name="extend" type="submit" value="5" class="btn btn-primary btn-block">+5</button>
            <button name="extend" type="submit" value="10" class="btn btn-primary btn-block">+10</button>
            <button name="extend" type="submit" value="30" class="btn btn-primary btn-block">+30</button>
            <button name="stop" type="submit " class="btn btn-danger btn-block">Stop</button>
        </div>
        {% endif %}
    </form>
    <div class="card-footer"><a href="{% url 'pomodoro:pomodoro-today' %}">Today</a></div>
</div>
{% endblock %}

pomodoro/templates/pomodoro/pomodoro_archive_day.html
{% extends "pomodoro/base.html" %}
{% load i18n %}
{% load pomodoro %}
{% load static %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:dashboard' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:pomodoro-list' %}">{% trans 'Archive' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:pomodoro-year' day.year %}">{{day|date:"Y"}}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:pomodoro-month' day.year day.month %}">{{day|date:"m"}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{day|date:"d"}}</li>
    </ol>
</nav>

{% latest_pomodoro %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if previous_day %}
        <li class="page-item">
            <a class="page-link" aria-label="Previous" href="{% url 'pomodoro:pomodoro-day' previous_day.year previous_day.month previous_day.day %}">
                <span aria-hidden="true">&laquo; {{previous_day|date}}</span>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" aria-label="Next" href="{% url 'pomodoro:pomodoro-day' day.year day.month day.day %}">
                <span aria-hidden="true">{{day|date}} &raquo;</span>
            </a>
        </li>
        {% if next_day %}
        <li class="page-item">
            <a class="page-link" aria-label="Next" href="{% url 'pomodoro:pomodoro-day' next_day.year next_day.month next_day.day %}">
                <span aria-hidden="true">{{next_day|date}} &raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

<div class="card">
    <h4 class="card-header">{{day}}</h4>
    <table class="table table-sm">
        <tr>
            <th>Title</th>
            <th>Project</th>
            <th>Memo</th>
            <th>Start</th>
            <th>End</th>
            <th>Duration</th>
        </tr>
        {% for p in pomodoro_list|dictsort:'start' %}
        <tr style="border-left: 10px solid {{p.project.color}}">
            <td><a href="{{p.get_absolute_url}}">{{p.title}}</a></td>
            <td><a href="{{p.project.get_absolute_url}}">{{p.project.name}}</a></td>
            <td>{{p.memo}}</td>
            <td>{{p.start}}</td>
            <td>{{p.end}}</td>
            <td>{{p.duration}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

pomodoro/templates/pomodoro/pomodoro_archive_month.html
{% extends "pomodoro/base.html" %}
{% load i18n %}
{% load pomodoro %}
{% load static %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:dashboard' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:pomodoro-list' %}">{% trans 'Archive' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:pomodoro-year' month.year %}">{{month|date:"Y"}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{month|date:"m"}}</li>
    </ol>
</nav>

{% latest_pomodoro %}

<div class="row mx-3">
    <div class="col-10">
        <div class="card">
            <h4 class="card-header">{{month|date:view.dtfmt}}</h4>
            <table class="table">
                <tr>
                    <th>Project</th>
                    <th>Duration</th>
                </tr>
                {% for project, duration in object_list|project_report|dictsortreversed:1 %}
                <tr>
                    <td><a href="{{project.get_absolute_url}}?{% range_qs start=month end=next_month %}">{{project.name}}</a></td>
                    <td>{{duration}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-2">
        {% spaceless %}
        <table class="table table-sm">
            <tr>
                <th colspan="8" class="text-center">
                    <a
                       href="{% url 'pomodoro:pomodoro-year' year=today.year %}">{{this_month|date:'Y'}}</a>
                </th>
            </tr>
            <tr>
                <th colspan="2" class="text-left">
                    <span aria-hidden="true">&laquo;</span>
                    <a
                       {% if previous_month > today %}class="text-secondary" {% endif %}
                       href="{% url 'pomodoro:pomodoro-month' previous_month.year previous_month.month %}">{{previous_month|date:'F'}}</a>
                </th>
                <th colspan="4" class="text-center">
                    <a
                       {% if this_month > today %}class="text-secondary" {% endif %}
                       href="{% url 'pomodoro:pomodoro-month' year=this_month.year month=this_month.month %}">{{this_month|date:'F'}}</a>
                </th>
                <th colspan="2" class="text-right">
                    <a
                       {% if next_month > today %}class="text-secondary" {% endif %}
                       href="{% url 'pomodoro:pomodoro-month' next_month.year next_month.month %}">{{next_month|date:'F'}}</a>
                    <span aria-hidden="true">&raquo;</span>
                </th>
            </tr>
            <tr>
                <th>&nbsp;</th>
                <th>{{calendar.0.0|date:'D'}}</th>
                <th>{{calendar.0.1|date:'D'}}</th>
                <th>{{calendar.0.2|date:'D'}}</th>
                <th>{{calendar.0.3|date:'D'}}</th>
                <th>{{calendar.0.4|date:'D'}}</th>
                <th>{{calendar.0.5|date:'D'}}</th>
                <th>{{calendar.0.6|date:'D'}}</th>
            </tr>
            {% for week in calendar %}
            <tr>
                <td class="table-secondary">
                    <span class=" text-secondary">{{week.0.isocalendar.1}}</a>
                </td>
                {% for d in week %}
                <td>
                    <a
                       {% if d > today %}class="text-secondary" {% endif %}
                       href="{% url 'pomodoro:pomodoro-day' d.year d.month d.day %}">{{d.day}}</a>
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        {% endspaceless %}
    </div>
</div>

{% endblock %}

pomodoro/templates/pomodoro/pomodoro_archive_year.html
{% extends "pomodoro/base.html" %}
{% load i18n %}
{% load pomodoro %}
{% load static %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:dashboard' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pomodoro:pomodoro-list' %}">{% trans 'Archive' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{year|date:view.dtfmt}}</li>
    </ol>
</nav>

{% latest_pomodoro %}

<div class="row mx-3">
    <div class="col-10">
        <div class="card">
            <h4 class="card-header">{{year|date:view.dtfmt}}</h4>
            <table class="table">
                <tr>
                    <th>Project</th>
                    <th>Duration</th>
                </tr>
                {% for project, duration in object_list|project_report|dictsortreversed:1 %}
                <tr>
                    <td><a href="{{project.get_absolute_url}}?{% range_qs start=year end=next_year %}">{{project.name}}</a></td>
                    <td>{{duration}}</td>
                </tr>
                {% endfor %}
            </table>

        </div>
    </div>
    <div class="col-2">
        <ul class="list-unstyled">
            {% for month in this_year %}
            <li>
                <a
                   {% if today <= month %}class="text-secondary" {% endif %}"
                   href="{% url 'pomodoro:pomodoro-month' month.year month.month %}">
                    {{month|date:"F"}}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

pomodoro/templates/pomodoro/pomodoro_list.html
{% extends "pomodoro/base.html" %}
{% load static %}
{% load pomodoro %}

{% block content %}

{% latest_pomodoro %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if date_prev %}
        <li class="page-item">
            <a class="page-link" aria-label="Previous" href="{% url 'pomodoro:pomodoro-list' date_prev|date:"Ymd" %}">
                <span aria-hidden="true">&laquo; {{date_prev|date}}</span>
            </a>
        </li>
        {% endif %}

        {% if date_next %}
        <li class="page-item">
            <a class="page-link" aria-label="Next" href="{% url 'pomodoro:pomodoro-list' date_next|date:"Ymd" %}">
                <span aria-hidden="true">{{date_next|date}} &raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
    
<div class="card">
    <h4 class="card-header">{{date}}</h4>
    <table class="table">
        <tr>
            <th>Title</th>
            <th>Project</th>
            <th>Category</th>
            <th>Start</th>
            <th>End</th>
            <th>Duration</th>
        </tr>
{% for p in pomodoro_list %}
        <tr>
            <td><a href="{{p.get_absolute_url}}">{{p.title}}</a></td>
            <td><a href="{{p.project.get_absolute_url}}">{{p.project.name}}</a></td>
            <td>{{p.category}}</td>
            <td>{{p.start}}</td>
            <td>{{p.end}}</td>
            <td>{{p.duration}}</td>
        </tr>
{% endfor %}
    </table>
</div>
{% endblock %}

pomodoro/templates/pomodoro/project_detail.html
{% extends "pomodoro/base.html" %}
{% load i18n %}
{% load pomodoro %}

{% block content %}

{% breadcrumb object %}

{% latest_pomodoro %}

<div class="card">
    <h4 class="card-header">{{object.name}}</h4>
    <table class="table table-sm">
        <tr style="border-left: 10px solid {{project.color}}">
            <th>Title</th>
            <td>{{object.name}}</td>
        </tr>
        <tr style="border-left: 10px solid {{project.color}}">
            <th>URL</th>
            <td>{{obj.url|urlize}}</td>
        </tr>
        <tr style="border-left: 10px solid {{project.color}}">
            <th>Memo</th>
            <td>{{object.memo}}</td>
        </tr>
    </table>
    <div class="card-footer">
        <a class="btn btn-sm btn-warning" href="{% url 'pomodoro:project-update' project.id %}">{% trans 'Change' %}</a>
    </div>
</div>
<br>

<div class="card">
    <h4 class="card-header">Favorites</h4>

    <table class="table table-sm">
        <tr>
            <th>Favorite</th>
            <th>Duration</th>
            <th>Count</th>
            <th>&nbsp;</th>
        </tr>
        {% for f in object.favorite_set.all %}
        <tr style="border-left: 10px solid {{project.color}}">
            <td>
                <form action="{% url 'pomodoro:favorite-detail' f.pk %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary btn-sm btn-block">
                        {{f.title}}
                    </button>
                </form>
            </td>
            <td>{{f.timedelta}}</td>
            <td>{{f.count}}</td>
            <td>
                <a class="btn btn-sm btn-warning" href="{% url 'pomodoro:favorite-detail' f.id %}">{% trans 'Change' %}</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No Favorites</td>
        </tr>
        {% endfor %}
    </table>
    <div class="card-footer">
        <a class="btn btn-sm btn-primary" href="{% url 'pomodoro:project-favorite-create' project.id %}">{% trans 'Add' %}</a>
    </div>
</div>
<br>

<div class="card">
    <h4 class="card-header">Recent</h4>
    <table class="table table-sm">
        <tr>
            <th>Pomodoro</th>
            <th>Start</th>
            <th>End</th>
            <th>Duration</th>
            <th>&nbsp;</th>
        </tr>
        {% for p in page_obj %}
        <tr style="border-left: 10px solid {{project.color}}">
            <td><a href="{{p.get_absolute_url}}">{{p.title}}</a></td>
            <td>{{p.start}}</td>
            <td>{{p.end}}</td>
            <td>{{p.duration}}</td>
            <td>
                <a class="row badge badge-warning" href="{% url 'pomodoro:pomodoro-detail' p.id %}">{% trans 'Change' %}</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No Pomodoros</td>
        </tr>
        {% endfor %}
    </table>
</div>
<br />

{% include 'pomodoro/pagination.html' %}

{% endblock %}

pomodoro/templates/pomodoro/project_list.html
{% extends "pomodoro/base.html" %}
{% load i18n %}
{% load pomodoro %}

{% block content %}

{% breadcrumb 'Projects' %}

{% latest_pomodoro %}

<h1>Projects</h1>
<a class="btn btn-sm btn-primary" href="{% url 'pomodoro:project-create'  %}">{% trans 'Add' %}</a>
<div class="card">
    <table class="table table-sm">
        <tr>
            <th colspan="2">Name</th>
            <th>Duration</th>
            <th>Link</th>
        </tr>
        {% for project in object_list %}
        <tr style="border-left: 10px solid {{project.color}}">
            <td><a href="{{project.get_absolute_url}}">{{project.name}}</a></td>
            <td><a class="badge badge-warning" href="{% url 'pomodoro:project-update' project.id %}">{% trans 'Change' %}</a></td>
            <td>{{project.timedelta}}</td>
            <td>{{project.url|urlize}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}